# Generated by Django 4.2.10 on 2024-03-09 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.CharField(max_length=255)),
                ('email_username', models.CharField(max_length=255)),
                ('email_password', models.CharField(max_length=255)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField()),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('imap_pop3_host', models.CharField(blank=True, max_length=255, null=True)),
                ('imap_pop3_port', models.IntegerField(blank=True, null=True)),
                ('email_protocol', models.CharField(blank=True, choices=[('IMAP', 'IMAP'), ('POP3', 'POP3')], max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date_received', models.DateTimeField()),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.emailsettings')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='main.emailmessage')),
            ],
        ),
    ]
